### PR TITLE
Be able to add package external EventHandlers

### PR DESCRIPTION
**Pull request by katringoogoo**
I added a new (backwards-compatible) way to specify the EventHandler in the config file e.g.

```
  event_handler:
    class: vsc_event_handler.VSCEventHandler
    config:
       <config object>
```

### CODE REVIEW

**Comment by venekamp** [comment]
I like the idea of being able to use external packages. Would it be possible for you to make the `name` a bit smarter? Then we don't need `name` and `class` to do basically the same thing. If the `name` value does not contain a '.', then it must be a class from the SRAMsync package. So then add the 'SRAMsync.' to make it a fully quantified name Python can load. If it does contain a period, then simply try to load it like you have done for the `class` implementation.

**Comment by venekamp** [comment]
Thanks for the additional explanation on the choice of adding the `class:` key.  I do like both approaches. Let's go with your original idea of making `name:` a bit more intelligent.

**Comment by katringoogoo** [comment]
Yes will do! Will also add a bit more text into the Readme about how to use it ...

**Comment by katringoogoo** [comment]
@venekamp I also added a simple test (via pytest). I wasn't using pipenv before so i'm not sure on how to properly update the lockfile without breaking anything (in a local test i got a lot of - probably unwanted - changes since i'm still using python 3.6 on the machine i'm running the code on).

**Comment by venekamp** [comment]
pipenv is not mandatory to use. It's just a way to setup a virtual environment and a means to install the same package versions that upstream has.  I think Python 3.6 should be okay. Until it was declared end-of-life, Python 3.6 was the lowest supported version. Am not using any 3.7 specifics.

**Comment by venekamp** [comment]
Thanks for extending the functionality.

**Pull request merged**
